### ISSUE TITLE
Workflow > Comments > User should not be allowed to edit the other's people reply

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#141]
https://share.vidyard.com/watch/cP8wQHUdaUAvEHwxgbwffj?

**Comment by bioworkflows** [comment]
During the video sham5 was already editing his own comments or replies. Are you saying that it should not be allowed to modify quoted texts?

**Comment by Mashhood-Ehsan** [comment]
Where "Shami5" is able to edit the "nobody" comment, and then reply to it.

![Screenshot (1441)](https://user-images.githubusercontent.com/60692597/199324177-8e8090d4-5726-4efb-93ed-5097dc32881d.png)

**Comment by bioworkflows** [comment]
ok, I see, Shami5 is replying to a comment, which cites the original content from nobody. This is actually by design, for example, if nobody has a very long message and Shami5 only wants to respond to one of the points, or if he want to split the original question and respond separately.

So essentially the quoted text is there just for convenience and Shami5 can remove all of them if he wants to start a new topic.

**Comment by Mashhood-Ehsan** [comment]
Ok, understood.
Thanks for clearing out the clarifications.
