### ISSUE TITLE
Workflow > Upload workflow > Workflow preview needs to be load fast, currently its takinng some time to load preview. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#161]
In the current scenario, the system first starts showing a preview message of the 'Jupyter Notebook' file loading, then 'Banner Image', and at the end ' Attachments'

https://share.vidyard.com/watch/uyLMAkHTA1cVXnmJDVq36q?

**Comment by BoPeng** [comment]
I am not sure what exactly to improve so 

1. I reserve the space for images before they are loaded to reduce element relayout.
2. Show images only when they are fully loaded so that they are not displayed "progressively".
3. Updated data processing prompts to be more consistent (e.g. Processing x/y/z ..)

**Comment by Mashhood-Ehsan** [comment]
Now, the performance is better and the content is loading fast as compared to last time. So closing this bug.

![Screenshot (1588)](https://user-images.githubusercontent.com/60692597/206004060-dfcd2ff6-5da7-4130-aac6-cea152a7cdc5.png)
