### ISSUE TITLE
Profile > User is following '2' users, but system is displaying the count as '3' users. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#182]
![7](https://user-images.githubusercontent.com/60692597/204344896-32cf7fa5-5cc2-4ff4-b813-ac32dfb1896f.PNG)

**Comment by bioworkflows** [comment]
The inconsistency was caused by prior testing. It does not worth the trouble to create a dedicate re-count mechanism for production, so I have updated the code to update the counts when the actual list is displayed and the number is inconsistent with the count.

That is to say, the problem will disappear after clicking `following` and the count will be correct the next time the page is visited.
