### ISSUE TITLE
Workflow > Publish New Workflow > One of the user from following's list has just published a workflow, but the other user did not receive notification related to that. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#184]
![9 (1)](https://user-images.githubusercontent.com/60692597/204350913-d5da4220-e23f-4b9b-9f61-bee7c579e027.PNG)
![9 (2)](https://user-images.githubusercontent.com/60692597/204350940-a5471dd5-4e2a-4564-97e5-fff81457cdbb.png)
![9 (3)](https://user-images.githubusercontent.com/60692597/204350964-fc5f92e1-b868-432f-87c1-059f65c590be.png)

**Comment by bioworkflows** [comment]
This is because the notification flag for `User_Workflow_By_FollowingUser` is currently off for `user1` although new users have this flag set by default.

![image](https://user-images.githubusercontent.com/47236991/205477481-c4eb939b-f803-4215-a7ad-fd7d734436b8.png)

After turning on this flag, notification should be received by `user1`.

**Comment by bioworkflows** [comment]
![image](https://user-images.githubusercontent.com/47236991/205477671-f52fe44c-194c-4348-a51d-d39565c5097b.png)

**Comment by Mashhood-Ehsan** [comment]
The issue is resolved, so closing it.

![Screenshot (1603)](https://user-images.githubusercontent.com/60692597/206011546-0da95878-97fb-4c44-bf1c-5d5ea7a70465.png)
