### ISSUE TITLE
Bounties > It's been one day (bounty question total limit) but Bounties without upvoted answers at the end of the bounty period are yet not being canceled

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#203]
![21](https://user-images.githubusercontent.com/60692597/208978333-bdc22f3b-adc1-4288-a88a-6c5e0854ada1.PNG)

![21 (2)](https://user-images.githubusercontent.com/60692597/208978356-d738a397-35fe-4e5e-896d-4c83467094ae.PNG)

**Comment by bioworkflows** [comment]
Every bounty is scheduled to be processed when it is expired (and canceled if valid answer is available). However, due to frequent reboot of the staging server, the tasks are lost before the bounties expired.

This lead to a more interesting topic regarding task persistency that we need to address.....

**Comment by bioworkflows** [comment]
Bounties that are failed to be processed when they are expired will be processed every day.

**Comment by Mashhood-Ehsan** [comment]
As per the comments, and after verifying it.
Closing the bug
