### ISSUE TITLE
Community Discussion Forum > When the bounty time period gets ended, system start displaying message '0 minutes remaining' instead of shwoing cancelled status.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#208]
![16](https://user-images.githubusercontent.com/60692597/208980100-63479f39-6a33-46fa-b2c8-b9a3ef9fa175.PNG)

**Comment by bioworkflows** [comment]
changed to expired. Every bounty is scheduled to be processed when it is expired (and canceled if valid answer is available), however, due to refresh reboot of the staging server, the tasks are lost before the bounties expired.

This lead to a more interesting topic regarding task persistency that we need to handle, but before that we have restored the bounty processing tasks.

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it after verifying.
