### ISSUE TITLE
User dashboard > My Withdrawals > When user click on the 'Request Withdrawl', sysetm don't respond back with any message/action and button become greyed-out. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#219]
![7](https://user-images.githubusercontent.com/60692597/215868557-a3fe2730-b700-49ae-a0e8-2b5138f79e46.PNG)

**Comment by bioworkflows** [comment]
According to the screenshot, "Request Withdrawal" should be grayed out from the beginning because the user did not enable "Stripe Payout", which would require user to register a stripe account (connect to stripe, from settings).

If the systems allow the button to be clicked (cursor change shape), and show no confirmation or error message after clicking, this would be a valid bug report.

**Comment by Mashhood-Ehsan** [comment]
When the amount was greater, the system display an error.

![7](https://user-images.githubusercontent.com/60692597/219971110-176f4cc4-ddab-4810-8e31-a3bc9c278efc.PNG)


and if the amount is smaller, the system will display a success message.

![Screenshot (1802)](https://user-images.githubusercontent.com/60692597/219971147-7453b3e3-b1f8-4d12-bb53-eeb420bd5de5.png)
