### ISSUE TITLE
Workflows from snakemake workflow catalog

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#310]
[Snakemake workflow catalog](https://snakemake.github.io/snakemake-workflow-catalog/)

There are more than 2000 workflows. They follow a certain standard so we are able to import the workflows and the snippets relatively easily. We have imported ten of them for testing.

1. These snakelike workflows **does not have to be biomedical**. If they do not handle biomedical data, click `...`, then `Report`, say `not biomedical`.
2. Many workflows lack a good title. The import script tires to use header etc but the title may need to be improved.
3. The biggest issue is with the description, which are often too long. We are trying to see if we can somehow shorten them (remove long sections)

**Comment by bioworkflows** [comment]
More workflows from this collection are being imported. Note that instead of trimming GitHub readme files, we have decided to incorporate complete readme files. This will reduce the need for manual curation and make future updates much easier.

So, **you do not need to update description**. If you notice something wrong, let us know and we will improve the import script.
