### ISSUE TITLE
Handling in-repository scripts

### ISSUE THREAD

**Issue by BoPeng** [bioworkflows/bioworkflows-help#315]
Affected workflows:

https://bioworkflows.com/public/public_trapseq.1/
https://bioworkflows.com/public/rnaseq.6/
https://bioworkflows.com/public/snakemake_align_majiq.1/

We have 

```
script:
    "./scripts/kallisto_deseq2.R"

```

```
script:
    "../scripts/count-matrix.py"

```

https://bioworkflows.com/public/phanta.1/#snippets (may have to add shell scripts manually)

```
shell: """
  python {params.repo_dir}/pipeline_scripts/prep_to_merge_normed.py \
  {input.tot_reads_file} {params.classdir} {input.failed_file}
  """
```

https://bioworkflows.com/public/tourmaline.1/#snippets

```
shell:
    "python scripts/plot_repseq_properties.py {input.lengths} {input.gaps} {input.outliers} {input.taxonomy} "
    "{input.table} {output.proptsv} {output.propdescribe} {output.proppdf} {output.outliersforqza}"
and we need to include the actual `R` script as snippets.
```

**Comment by bioworkflows** [comment]
We have been working on importing Python, R, and shell scripts from the workflows, because many snippets only have things like `shell process.sh`.  Workflows listed here are processed and all existing workflows will be re-processed in the next day or two.

Note that:
1.  Python and R scripts have clear signals such as `import` and `library`. We only need to pay attention to unfamiliar modules and libraries, which could be from tools such as `bioconductor`. 
2. Shell scripts are a lot harder but we have done that repeatedly.
3. If a workflow has very few snippets, it may contain un-identified scripts. Please report the workflows here.
4. Scripts importing are currently only enabled for snakemake workflows. If you encounter similar "scripts" for other workflows, please report the workflows here.

**Comment by bioworkflows** [comment]
Absolute path is not handled correctly.

https://bioworkflows.com/public/crispri-flowfish.1/
