### ISSUE TITLE
Login > Creat a new users. Then login with same user. On clicking the login button, system start displaying the white screen.

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#75]
https://share.vidyard.com/watch/NgQk6jj7PY4nwstSu6Scnt

**Comment by BoPeng** [comment]
I can reproduce the problem but strangely there is no error message anywhere. Let me check.

**Comment by BoPeng** [comment]
OK. The email is not verified after I verify the email address. This is a third-party module and I will have to check what is going on there.

I have manually verified your account and you should be able to login now.

**Comment by BoPeng** [comment]
OK, this is caused by a new version of django-allauth, which changed the email confirmation behavior. I have fixed the email confirmation process, but the "blank" screen problem is still there if the user tries to login without confirming the email address.

I have submitted a ticket to the upstream https://github.com/pennersr/django-allauth/issues/3144

**Comment by BoPeng** [comment]
Should have been fixed.

**Comment by Mashhood-Ehsan** [comment]
Okay, thanks for the update.

**Comment by Mashhood-Ehsan** [comment]
The issue is not occurring anymore, so closing it.

![10](https://user-images.githubusercontent.com/60692597/191612468-84b78bb1-77e5-4b29-95d6-ea2790c12f8f.PNG)
