### ISSUE TITLE
Workflow > Purchase workflow > When user click on 'Purchase workflow' button, workflow should be added to cart. 

### ISSUE THREAD

**Issue by Mashhood-Ehsan** [bioworkflows/bioworkflows-help#87]
Currently, user has been navigated to the details page, instead of adding workflow to the cart. 

https://share.vidyard.com/watch/JZakdYQaLod7V7MqwQdv8e?

**Comment by bioworkflows** [comment]
This has been fixed, actually the entire checkout system has been redesigned. Note that

1. If the user has enough balance, the balance will be used and a confirmation page will be shown.
2. Otherwise the user will go to checkout page directly
3. If user only want to add to cart, the right hand side "add-to-cart" button should be used.

To test balance-related checkout, buy a credit using card 42424242... , or redeem a gift card of number 0000 0000 000000

**Comment by Mashhood-Ehsan** [comment]
The issue is fixed now, so closing it.

![Screenshot (1269)](https://user-images.githubusercontent.com/60692597/191599898-3ea2561d-4ec5-4185-a912-742f1dd76606.png)
![Screenshot (1264)](https://user-images.githubusercontent.com/60692597/191599937-fc69c1a7-95a4-4f2a-baf6-0ca8864ab481.png)
